name: Deploy Latest Model

on:
  workflow_run:
    workflows: ["Retrain PDF Multimodal Model"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - name: Deploy Vertex AI Model to Endpoint
        run: |
          NEW_MODEL_ID="<NEW_MODEL_ID_FROM_TRAINING_OUTPUT>"
          ENDPOINT_ID="<EXISTING_VERTEX_AI_ENDPOINT_ID>"
          gcloud ai endpoints deploy-model $ENDPOINT_ID \
            --model=$NEW_MODEL_ID \
            --region=${{ secrets.GCP_REGION }} \
            --display-name="pdf-multimodal-endpoint" \
            --traffic-split=0=100
