name: Retrain PDF Multimodal Model

on:
  schedule:
    - cron: '0 2 * * 1'  # every Monday 2 AM UTC
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - name: Start Vertex AI Custom Training Job
        run: |
          gcloud ai custom-jobs create \
            --region=${{ secrets.GCP_REGION }} \
            --display-name="pdf-multimodal-retrain" \
            --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,executor-image-uri=us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-11:latest,local-package-path=trainer,python-module=trainer.task \
            --args="--train_data_gcs=gs://my-10k-reports/pdfs/ --other_config=..."
